Repository Mod-4-Capstone/we-the-people-fe, pull requests merged in 2022-05, with the labels that each got.

#1 Initial setup/ml
  .github/workflows/main.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/landing_page_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/apiCalls.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Layout/Layout.css
  src/components/Layout/Layout.js
  src/components/MainDash/MainDash.css
  src/components/MainDash/MainDash.js
  src/components/Quiz/Quiz.css
  src/components/Quiz/Quiz.js
  src/components/QuizForm/QuizForm.css
  src/components/QuizForm/QuizForm.js
  src/components/QuizResults/QuizResults.css
  src/components/QuizResults/QuizResults.js
  src/components/RepCard/RepCard.css
  src/components/RepCard/RepCard.js
  src/components/RepContainer/RepContainer.css
  src/components/RepContainer/RepContainer.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: setup

#5 Inital component build/zl
  public/index.html
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Layout/Layout.js
  src/components/MainDash/MainDash.js
  src/components/Quiz/Quiz.css
  src/components/Quiz/Quiz.js
  src/components/QuizResults/QuizResults.js
  src/components/RepCard/RepCard.css
  src/components/RepCard/RepCard.js
  src/components/RepContainer/RepContainer.js
  src/components/Statement/statement.css
  src/components/Statement/statement.js
  src/index.css
Labels: feature / enhancement

#8 Temp data/ml
  src/components/RepCard/RepCard.js
  src/components/RepContainer/RepContainer.js
  src/data/data.js
Labels: feature / enhancement, FE

#10 Header/zl
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Quiz/Quiz.js
Labels: feature / enhancement, styling

#11 Context/nv
  src/components/App/App.js
  src/components/RepCard/RepCard.css
  src/components/RepCard/RepCard.js
  src/components/RepContainer/RepContainer.js
  src/contexts/DataContext.js
  src/data/data.js
Labels: feature / enhancement, FE

#19 Rep card default/ml
  src/components/Quiz/Quiz.js
  src/components/QuizResults/QuizResults.js
  src/components/RepCard/RepCard.css
  src/components/RepCard/RepCard.js
  src/components/RepContainer/RepContainer.js
  src/components/StateDropdown/StateDropdown.js
Labels: refactor / bug, FE

#28 State dropdown with quiz/zl
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Loader/Loader.css
  src/components/Loader/Loader.js
  src/components/MainDash/MainDash.js
  src/components/Quiz/Quiz.css
  src/components/Quiz/Quiz.js
  src/components/QuizResults/QuizResults.js
  src/components/RepCard/RepCard.js
  src/components/StateDropdown/StateDropdown.css
  src/components/StateDropdown/StateDropdown.js
  src/contexts/DataContext.js
Labels: feature / enhancement, styling

#29 Error handling/ml
  src/apiCalls.js
  src/assets/senate.png
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Header/Header.js
  src/components/MainDash/MainDash.js
  src/components/Quiz/Quiz.js
  src/components/RepCard/RepCard.css
  src/components/RepCard/RepCard.js
  src/components/RepRatings/RepRatings.css
  src/components/RepRatings/RepRatings.js
  src/components/StateDropdown/StateDropdown.js
  src/contexts/DataContext.js
  src/data/data.js
Labels: refactor / bug, feature / enhancement, FE

#30 Dropdownfix/jf
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/StateDropdown/StateDropdown.css
  src/components/StateDropdown/StateDropdown.js
Labels: feature / enhancement

#32 Modal quiz results/ml
  package-lock.json
  package.json
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Loader/Loader.css
  src/components/QuizResults/QuizResults.css
  src/components/QuizResults/QuizResults.js
  src/components/QuizResultsModal/QuizResultsModal.css
  src/components/QuizResultsModal/QuizResultsModal.js
  src/components/RepCard/RepCard.css
  src/components/RepCard/RepCard.js
  src/components/RepRatings/RepRatings.css
  src/components/StateDropdown/StateDropdown.css
  src/components/StateDropdown/StateDropdown.js
Labels: feature / enhancement, styling, FE

#33 Cypress2/nv
  cypress/fixtures/example.json
  cypress/fixtures/legislatorData.json
  cypress/integration/landing_page_spec.js
  src/components/Quiz/Quiz.js
  src/components/Statement2/Statement2.js
Labels: testing, FE

#34 Cd/zl
  .github/workflows/deploy.yml
  README.md
Labels: feature / enhancement, FE

#35 Styling quiz results/ml
  package-lock.json
  package.json
  src/components/DoughnutChart/DoughnutChart.css
  src/components/DoughnutChart/DoughnutChart.js
  src/components/Quiz/Quiz.css
  src/components/QuizResults/QuizResults.css
  src/components/QuizResults/QuizResults.js
  src/components/QuizResultsModal/QuizResultsModal.css
  src/components/QuizResultsModal/QuizResultsModal.js
  src/components/RepCard/RepCard.css
  src/components/RepRatings/RepRatings.css
  src/components/StateDropdown/StateDropdown.js
  src/components/Statement2/Statement2.css
Labels: styling, FE

#36 Cypress3/nv
  cypress/fixtures/stateLegislatorData.json
  cypress/integration/results_with_quiz_spec.js
  cypress/integration/results_with_state_spec.js
  cypress/integration/state_only_spec.js
  src/components/QuizResults/QuizResults.js
  src/components/RepCard/RepCard.js
  src/components/RepRatings/RepRatings.js
Labels: FE

#38 Refactor/zl
  README.md
  src/apiCalls.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/DoughnutChart/DoughnutChart.css
  src/components/DoughnutChart/DoughnutChart.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Layout/Layout.css
  src/components/Layout/Layout.js
  src/components/Loader/Loader.css
  src/components/Loader/Loader.js
  src/components/MainDash/MainDash.css
  src/components/MainDash/MainDash.js
  src/components/Quiz/Quiz.css
  src/components/Quiz/Quiz.js
  src/components/QuizResults/QuizResults.css
  src/components/QuizResults/QuizResults.js
  src/components/QuizResultsModal/QuizResultsModal.css
  src/components/QuizResultsModal/QuizResultsModal.js
  src/components/RepCard/RepCard.css
  src/components/RepCard/RepCard.js
  src/components/RepContainer/RepContainer.css
  src/components/RepContainer/RepContainer.js
  src/components/RepRatings/RepRatings.css
  src/components/RepRatings/RepRatings.js
  src/components/StateDropdown/StateDropdown.css
  src/components/StateDropdown/StateDropdown.js
  src/components/Statement/statement.css
  src/components/Statement/statement.js
  src/components/Statement2/Statement2.css
  src/components/Statement2/Statement2.js
  src/contexts/DataContext.js
  src/data/data.js
  src/index.js
Labels: refactor / bug, FE

#39 Add responsiveness to quiz results page
  src/components/QuizResults/QuizResults.css
Labels: FE

#41 Refactor3/nv
  src/components/QuizResultsModal/QuizResultsModal.css
  src/components/QuizResultsModal/QuizResultsModal.js
  src/components/RepContainer/RepContainer.css
Labels: feature / enhancement, FE
